Modify login
kotapiku/mercari-build-hackathon-2023 pull request #13
Opened 2023-05-24 13:17 UTC by aki2130

## What
usernameでログインできるようにfrontendの仕様を変更しました

## Why

## 変更箇所
- [x] frontend
- [ ] backend

2023-05-25 06:42 UTC, nachan28 reviewed
![image](https://github.com/kotapiku/mercari-build-hackathon-2023/assets/105186662/74ad6e62-b8e6-4eed-8e4f-0c29c9a83ce1)
いくつか消したコンポーネントのimport文が残ってたりしてエラー出てるっぽい？

2023-05-25 10:11 UTC, kotapiku requested changes
backendにあわせてリクエストの修正をお願いします！
一度logoutしてからloginできるか動作確認もできればお願いします。

2023-05-25 10:11 UTC, kotapiku commented on frontend/simple-mercari-web/src/components/Login/Login.tsx
> +          placeholder="name"
名前でログインする場合、/loginではなく、/login_nameエンドポイントを使う必要があるので、onSubmitのfetcherの部分も修正をお願いします！:bow:
リクエストボディはuser_idではなくuser_nameを使ってください。

2023-05-25 10:11 UTC, kotapiku commented on frontend/simple-mercari-web/src/components/Signup/Signup.tsx
これ消して大丈夫なファイルでしょうか？

2023-05-25 10:11 UTC, kotapiku commented on frontend/simple-mercari-web/src/components/UserProfile/UserProfile.tsx
こちらも消して大丈夫なファイルでしょうか？

2023-05-25 10:13 UTC, kotapiku commented on frontend/simple-mercari-web/src/components/Login/Login.tsx
> +          placeholder="name"
#15 をマージしたあとにこちらの修正を確認するのがいいかもです

2023-05-27 03:50 UTC, kotapiku approved these changes
LGTM!

2023-05-27 12:16 UTC, merged